### PR TITLE
Cleanup LinkAccountSubtype interface and update iOS bridge code to support new account subtype format

### PR DESCRIPTION
**Pull request by pladaub**
1. LinkAccountSubtypeInterface seems like an unfortunate name to publicize when LinkAccountSubtype is no longer private
2. Updating the iOS code to parse the newly formatted account subtypes

### CODE REVIEW

**Review by zsweigart — APPROVED** [review]
The rename seems reasonable to me, the only concern would be that there is really no use for `LinkAccountSubtype` other than a place holder where `LinkAccountSubtypeInterface` makes that more explicit

**Review by JeroenMols — APPROVED** [review]
Great improvement, thanks for picking this up!

**Comment by amytang0** [comment]
@zsweigart @JeroenMols are we directly referencing these types in the Android code? Will we need to update that as well?

**Comment by zsweigart** [comment]
@amytang0 no we don't reference the type, we reference the field name `accountSubtypes` so they type change won't affect this

**Comment by amytang0** [comment]
LGTM, thanks for sprucing this up @pladaub!

**Pull request merged**
