### PR TITLE
Using native-base Button instead of react-native for better customization

### PR DESCRIPTION
**Pull request by ajaynaik20**
…tion

### CODE REVIEW

**Comment by edo1493** [comment]
I would also add that it's probably better if the library exports the openPlaid method rather than returning a view with a button. 😅

**Comment by Mande3p** [comment]
@wkiefer Sorry not the right place, but documentation seems to be incomplete for android.

`Add Plaid.create(this); in public void onCreate()` gives issues. There is no onCreate Method in MainApplication.java, even if you create one, it throws an error:
` cannot find symbol Plaid.create(this);`

**Comment by wkiefer** [comment]
Thanks for all the feedback! We'll be releasing v1.0.2 within the next day to fix the title issue and update some missing documentation.

I agree with your request to expose `openLink`, thanks.

I'll keep this PR open until the changes I mention are merged.

**Comment by wkiefer** [comment]
[v1.0.2](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v1.0.2) is out and also published to NPM.

We've incorporated the title fix from this diff, and updated the documentation to clarify the Android issue mentioned above.

We will also be exporting the `openLink` method in an upcoming release to give better flexibility beyond React Native's `Button` component.

**Pull request closed without merging**
