### PR TITLE
update kotlin graddle plugin to supports rn 0.71

### PR DESCRIPTION
**Pull request by Pedroor**
<h1 align="center">
  Testing
</h1>

kotlin gradle plugin is deprecated for rn 0.71

### CODE REVIEW

**Comment by molchanovskiy** [comment]
When this will become available?

**Review by molchanovskiy — APPROVED** [review]

**Comment by ally-henry** [comment]
Also waiting on this!

**Comment by Pedroor** [comment]
An alternative solution would be to create a fork, apply the changes and install the package directly from the repo.

`in package.json put "react-native-plaid-link-sdk": "https://github.com/Pedroor/react-native-plaid-link-sdk.git"`

**Review by priyeshshah11 — APPROVED** [review]

**Comment by priyeshshah11** [comment]
@wkiefer Any updates on this? looks like several others are waiting on this

**Review by lprhodes — APPROVED** [review]
Looks ready to go.

**Review by ezekielcb — APPROVED** [review]
Looks good, in supporting react native 0.71.*

**Review by RicoCallirgos — APPROVED** [review]

**Review by youssdevx — APPROVED** [review]
✅

**Comment by lexer** [comment]
Please merge this! This is blocking RN 0.71

**Review by samyos — APPROVED** [review]

**Review by Vadko — APPROVED** [review]

**Comment by alexlukelevy** [comment]
Yes, please merge this - it's blocking our Plaid integration atm.

**Review by dnelsonlivecurrence — APPROVED** [review]

**Comment by youssdevx** [comment]
Thanks @dtroupe-plaid 🙏🏽

**Comment by dnelsonlivecurrence** [comment]
Thanks @dtroupe-plaid, can't wait for this to be released

**Comment by leondavidtb** [comment]
✅

**Pull request merged**
